declare -x ADDR2LINE="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-addr2line"
declare -x AR="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ar"
declare -x AS="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-as"
declare -x BAMF_DESKTOP_FILE_HINT="/var/lib/snapd/desktop/applications/pycharm-community_pycharm-community.desktop"
declare -x BUILD="x86_64-conda-linux-gnu"
declare -x CC="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-cc"
declare -x CC_FOR_BUILD="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-cc"
declare -x CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include"
declare -x CMAKE_ARGS="-DCMAKE_AR=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-strip"
declare -x CMAKE_PREFIX_PATH="/home/jj/anaconda3/envs/browser:/home/jj/anaconda3/envs/browser/x86_64-conda-linux-gnu/sysroot/usr"
declare -x CONDA_BACKUP_FC_FOR_BUILD="/home/jj/miniconda3/envs/mason/bin/x86_64-conda-linux-gnu-gfortran"
declare -x CONDA_BUILD_SYSROOT="/home/jj/anaconda3/envs/browser/x86_64-conda-linux-gnu/sysroot"
declare -x CONDA_DEFAULT_ENV="browser"
declare -x CONDA_EXE="/home/jj/miniconda3/bin/conda"
declare -x CONDA_PREFIX="/home/jj/anaconda3/envs/browser"
declare -x CONDA_PREFIX_1="/home/jj/miniconda3"
declare -x CONDA_PREFIX_2="/home/jj/miniconda3/envs/mason"
declare -x CONDA_PROMPT_MODIFIER="(browser) "
declare -x CONDA_PYTHON_EXE="/home/jj/miniconda3/bin/python"
declare -x CONDA_SHLVL="3"
declare -x CONDA_TOOLCHAIN_BUILD="x86_64-conda-linux-gnu"
declare -x CONDA_TOOLCHAIN_HOST="x86_64-conda-linux-gnu"
declare -x CPP="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-cpp"
declare -x CPPFLAGS="-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jj/anaconda3/envs/browser/include"
declare -x CXX="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-c++"
declare -x CXXFILT="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-c++filt"
declare -x CXXFLAGS="-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include"
declare -x CXX_FOR_BUILD="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-c++"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
declare -x DEBUG_CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include"
declare -x DEBUG_CPPFLAGS="-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/jj/anaconda3/envs/browser/include"
declare -x DEBUG_CXXFLAGS="-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include"
declare -x DEBUG_FFLAGS="-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe"
declare -x DEBUG_FORTRANFLAGS="-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe"
declare -x DEFAULTS_PATH="/usr/share/gconf/ubuntu.default.path"
declare -x DESKTOP_SESSION="ubuntu"
declare -x DESKTOP_STARTUP_ID="gnome-shell/PyCharm Community Edition/2248-3-jj-ThinkPad-T590_TIME540596"
declare -x DISPLAY=":0"
declare -x ELFEDIT="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-elfedit"
declare -x F77="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gfortran"
declare -x F90="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gfortran"
declare -x F95="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-f95"
declare -x FC="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gfortran"
declare -x FFLAGS="-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include"
declare -x FORTRANFLAGS="-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jj/anaconda3/envs/browser/include"
declare -x GCC="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc"
declare -x GCC_AR="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-ar"
declare -x GCC_NM="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-nm"
declare -x GCC_RANLIB="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gcc-ranlib"
declare -x GDMSESSION="ubuntu"
declare -x GFORTRAN="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gfortran"
declare -x GIO_LAUNCHED_DESKTOP_FILE="/var/lib/snapd/desktop/applications/pycharm-community_pycharm-community.desktop"
declare -x GIO_LAUNCHED_DESKTOP_FILE_PID="6847"
declare -x GJS_DEBUG_OUTPUT="stderr"
declare -x GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
declare -x GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
declare -x GNOME_SHELL_SESSION_MODE="ubuntu"
declare -x GPG_AGENT_INFO="/run/user/1000/gnupg/S.gpg-agent:0:1"
declare -x GPROF="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-gprof"
declare -x GTK_MODULES="gail:atk-bridge"
declare -x GXX="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-g++"
declare -x HOME="/home/jj"
declare -x HOST="x86_64-conda-linux-gnu"
declare -x IM_CONFIG_PHASE="1"
declare -x INVOCATION_ID="7f0b2b8b11ce49459262e55170dd7075"
declare -x JAVA_HOME="/home/jj/anaconda3/envs/browser"
declare -x JAVA_HOME_CONDA_BACKUP=""
declare -x JAVA_LD_LIBRARY_PATH="/home/jj/anaconda3/envs/browser/lib/server"
declare -x JAVA_LD_LIBRARY_PATH_BACKUP=""
declare -x JOURNAL_STREAM="8:60686"
declare -x LANG="en_US.UTF-8"
declare -x LC_ADDRESS="de_DE.UTF-8"
declare -x LC_IDENTIFICATION="de_DE.UTF-8"
declare -x LC_MEASUREMENT="de_DE.UTF-8"
declare -x LC_MONETARY="de_DE.UTF-8"
declare -x LC_NAME="de_DE.UTF-8"
declare -x LC_NUMERIC="de_DE.UTF-8"
declare -x LC_PAPER="de_DE.UTF-8"
declare -x LC_TELEPHONE="de_DE.UTF-8"
declare -x LC_TIME="de_DE.UTF-8"
declare -x LD="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ld"
declare -x LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/jj/anaconda3/envs/browser/lib -Wl,-rpath-link,/home/jj/anaconda3/envs/browser/lib -L/home/jj/anaconda3/envs/browser/lib"
declare -x LD_GOLD="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ld.gold"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="jj"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MANAGERPID="2016"
declare -x MANDATORY_PATH="/usr/share/gconf/ubuntu.mandatory.path"
declare -x NM="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-nm"
declare -x OBJCOPY="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-objcopy"
declare -x OBJDUMP="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-objdump"
declare -x OLDPWD="/home/jj/Documents/mason"
declare -x PATH="/home/jj/perl5/bin:/home/jj/anaconda3/envs/browser/bin:/home/jj/miniconda3/condabin:/home/jj/.local/bin:/home/jj/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x PERL5LIB="/home/jj/perl5/lib/perl5"
declare -x PERL_LOCAL_LIB_ROOT="/home/jj/perl5"
declare -x PERL_MB_OPT="--install_base \"/home/jj/perl5\""
declare -x PERL_MM_OPT="INSTALL_BASE=/home/jj/perl5"
declare -x PWD="/home/jj/Documents/mason/commandline_version"
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="ibus"
declare -x RANLIB="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-ranlib"
declare -x READELF="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-readelf"
declare -x RSTUDIO_WHICH_R="/home/jj/anaconda3/envs/browser/bin/R"
declare -x SESSION_MANAGER="local/jj-ThinkPad-T590:@/tmp/.ICE-unix/2234,unix/jj-ThinkPad-T590:/tmp/.ICE-unix/2234"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SIZE="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-size"
declare -x SNAP="/snap/pycharm-community/274"
declare -x SNAP_ARCH="amd64"
declare -x SNAP_COMMON="/var/snap/pycharm-community/common"
declare -x SNAP_CONTEXT="CuH1XXOOY5gL1ZjOLf0BoGenK5Qzz8RSjWPoAiPIjWHzk4jT0poh"
declare -x SNAP_COOKIE="CuH1XXOOY5gL1ZjOLf0BoGenK5Qzz8RSjWPoAiPIjWHzk4jT0poh"
declare -x SNAP_DATA="/var/snap/pycharm-community/274"
declare -x SNAP_INSTANCE_KEY=""
declare -x SNAP_INSTANCE_NAME="pycharm-community"
declare -x SNAP_LIBRARY_PATH="/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void"
declare -x SNAP_NAME="pycharm-community"
declare -x SNAP_REAL_HOME="/home/jj"
declare -x SNAP_REEXEC=""
declare -x SNAP_REVISION="274"
declare -x SNAP_USER_COMMON="/home/jj/snap/pycharm-community/common"
declare -x SNAP_USER_DATA="/home/jj/snap/pycharm-community/274"
declare -x SNAP_VERSION="2021.3.3"
declare -x SSH_AGENT_PID="2196"
declare -x SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"
declare -x STRINGS="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-strings"
declare -x STRIP="/home/jj/anaconda3/envs/browser/bin/x86_64-conda-linux-gnu-strip"
declare -x TERM="xterm-256color"
declare -x TERMINAL_EMULATOR="JetBrains-JediTerm"
declare -x TERM_SESSION_ID="c3cc574c-1a6c-4b2c-911b-f235765d17d6"
declare -x USER="jj"
declare -x USERNAME="jj"
declare -x WINDOWPATH="2"
declare -x XAUTHORITY="/run/user/1000/gdm/Xauthority"
declare -x XDG_CONFIG_DIRS="/etc/xdg/xdg-ubuntu:/etc/xdg"
declare -x XDG_CURRENT_DESKTOP="ubuntu:GNOME"
declare -x XDG_DATA_DIRS="/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
declare -x XDG_MENU_PREFIX="gnome-"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SESSION_CLASS="user"
declare -x XDG_SESSION_DESKTOP="ubuntu"
declare -x XDG_SESSION_TYPE="x11"
declare -x XMODIFIERS="@im=ibus"
declare -x _CE_CONDA=""
declare -x _CE_M=""
declare -x _CONDA_PYTHON_SYSCONFIGDATA_NAME="_sysconfigdata_x86_64_conda_cos6_linux_gnu"
declare -x build_alias="x86_64-conda-linux-gnu"
declare -x host_alias="x86_64-conda-linux-gnu"
